# Gradle JVM
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# R class optimization
android.nonTransitiveRClass=true
